# frozen_string_literal: true

source 'https://rubygems.org'
source 'https://gems.theboton.io:8443'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem 'boton', '~> 0.20'
gem 'pry'
gem 'faraday'
